/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event;

import DB.DBConnection;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Inshu
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    public Admin(String u) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        addven = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        newbook = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bookhis = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        viewven = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        addemp = new javax.swing.JInternalFrame();
        jPanel32 = new javax.swing.JPanel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel134 = new javax.swing.JLabel();
        jTextField46 = new javax.swing.JTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jFormattedTextField22 = new javax.swing.JFormattedTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        viewemp = new javax.swing.JInternalFrame();
        jPanel34 = new javax.swing.JPanel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel147 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();
        jFormattedTextField19 = new javax.swing.JFormattedTextField();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jFormattedTextField23 = new javax.swing.JFormattedTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jFormattedTextField24 = new javax.swing.JFormattedTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel151 = new javax.swing.JLabel();
        jTextField57 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Logout");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 230, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Event Management System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 0, 489, 60));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Admin Module");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 245, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addven.setClosable(true);
        addven.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addven.setTitle("Add Venue");
        addven.setVisible(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Add Venue");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Rupees                     :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Image Upload   :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, 20));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Venue Address  :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Venue Phone No.:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jTextField2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 280, -1));

        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 280, 20));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Click here");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 120, 40));

        jTextField3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 280, -1));

        jFormattedTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 280, 20));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText(" Capacity                :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText(" Preferred For          :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jFormattedTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 280, 20));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Venue Name     :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 20));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Submit");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 120, 40));

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 330, 280));

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select-----", "Marriage", "Meeting", "Auction", "Birthday", "Ring Ceremony", "Kitty Party" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(56, 30));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 280, -1));

        javax.swing.GroupLayout addvenLayout = new javax.swing.GroupLayout(addven.getContentPane());
        addven.getContentPane().setLayout(addvenLayout);
        addvenLayout.setHorizontalGroup(
            addvenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addvenLayout.setVerticalGroup(
            addvenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(addven, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1060, 700));

        newbook.setClosable(true);
        newbook.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        newbook.setTitle("New Booking");
        newbook.setVisible(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("New Booking");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Status                     :");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        jTextField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 280, -1));

        jTextField5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 280, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Booking ID              :");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, 20));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Search");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 120, 30));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Change                 :");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select-----", "Seen", "Approved" }));
        jComboBox3.setPreferredSize(new java.awt.Dimension(56, 30));
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 280, -1));

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Submit");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 120, 40));

        jScrollPane1.setBorder(null);

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(22);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 980, 310));

        javax.swing.GroupLayout newbookLayout = new javax.swing.GroupLayout(newbook.getContentPane());
        newbook.getContentPane().setLayout(newbookLayout);
        newbookLayout.setHorizontalGroup(
            newbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        newbookLayout.setVerticalGroup(
            newbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(newbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1060, 700));

        bookhis.setClosable(true);
        bookhis.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        bookhis.setTitle("Booking History");
        bookhis.setVisible(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Bookings");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jScrollPane2.setBorder(null);

        jTable2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setRowHeight(22);
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 980, 470));

        javax.swing.GroupLayout bookhisLayout = new javax.swing.GroupLayout(bookhis.getContentPane());
        bookhis.getContentPane().setLayout(bookhisLayout);
        bookhisLayout.setHorizontalGroup(
            bookhisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bookhisLayout.setVerticalGroup(
            bookhisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(bookhis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1060, 700));

        viewven.setClosable(true);
        viewven.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        viewven.setTitle("New Booking");
        viewven.setVisible(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Venues");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel41.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Search");
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 120, 40));

        jLabel42.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Function                   :");
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jComboBox5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select-----", "Marriage", "Meeting", "Auction", "Birthday", "Ring Ceremony", "Kitty Party" }));
        jComboBox5.setPreferredSize(new java.awt.Dimension(56, 30));
        jPanel6.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 280, 40));

        jScrollPane3.setBorder(null);

        jTable3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setRowHeight(22);
        jTable3.setShowHorizontalLines(false);
        jTable3.setShowVerticalLines(false);
        jScrollPane3.setViewportView(jTable3);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 980, 440));

        javax.swing.GroupLayout viewvenLayout = new javax.swing.GroupLayout(viewven.getContentPane());
        viewven.getContentPane().setLayout(viewvenLayout);
        viewvenLayout.setHorizontalGroup(
            viewvenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        viewvenLayout.setVerticalGroup(
            viewvenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(viewven, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1060, 700));

        addemp.setClosable(true);
        addemp.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addemp.setTitle("Add Employee");
        addemp.setVisible(false);
        addemp.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel124.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel124.setText("Employee Id is (Auto-Generated)");
        jPanel32.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel125.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel125.setText("Aadhar No.               :");
        jPanel32.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel126.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel126.setText("Designation         :");
        jPanel32.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel127.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel127.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel127.setText("Gender                     :");
        jPanel32.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel128.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel128.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel128.setText("Mobile Number       :");
        jPanel32.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jLabel129.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel129.setText("Email Address           :");
        jPanel32.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        jLabel130.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel130.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel130.setText("Date Of Joining         :");
        jPanel32.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        jLabel132.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel132.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel132.setText("Address                    :");
        jPanel32.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        jLabel133.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel133.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel133.setText("Password                  :");
        jPanel32.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));

        jLabel134.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel134.setText("Add Employee");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(jLabel134)
                .addContainerGap(472, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel134, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        jTextField46.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField46.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel32.add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 270, -1));

        jFormattedTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jFormattedTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel32.add(jFormattedTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 270, 30));

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jRadioButton5.setText("Male");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel32.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jRadioButton6.setText("Female");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel32.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jTextField47.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField47.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel32.add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 270, -1));

        jTextField48.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField48.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel32.add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 270, -1));

        jTextField50.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField50.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel32.add(jTextField50, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 270, -1));

        jLabel135.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel135.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel135.setText("Employee Name     :");
        jPanel32.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel136.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel136.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel136.setText("Cancel");
        jLabel136.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel32.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 120, 40));

        jLabel137.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel137.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel137.setText("Submit");
        jLabel137.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel137.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel137MouseClicked(evt);
            }
        });
        jPanel32.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 120, 40));

        jFormattedTextField22.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jFormattedTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel32.add(jFormattedTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 270, 30));

        jPasswordField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel32.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 270, 30));
        jPanel32.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 270, 40));

        addemp.getContentPane().add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        jDesktopPane1.add(addemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 1070, 580));

        viewemp.setClosable(true);
        viewemp.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        viewemp.setTitle("View Employee");
        viewemp.setVisible(false);
        viewemp.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel139.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel139.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel139.setText("Aadhar No.         :");
        jPanel34.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        jLabel140.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel140.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel140.setText("Designation         :");
        jPanel34.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        jLabel141.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel141.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel141.setText("Gender                     :");
        jPanel34.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        jLabel142.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel142.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel142.setText("Mobile Number       :");
        jPanel34.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        jLabel143.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel143.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel143.setText("Email Address           :");
        jPanel34.add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jLabel144.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel144.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel144.setText("Date Of Joining          :");
        jPanel34.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        jLabel145.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel145.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel145.setText("Address                    :");
        jPanel34.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        jPanel35.setBackground(new java.awt.Color(102, 51, 0));

        jLabel147.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel147.setForeground(new java.awt.Color(255, 255, 255));
        jLabel147.setText("View Employee");

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(jLabel147)
                .addContainerGap(456, Short.MAX_VALUE))
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel147, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel34.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        jTextField52.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField52.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel34.add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 270, -1));

        jFormattedTextField19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jFormattedTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel34.add(jFormattedTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 270, 30));

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jRadioButton7.setText("Male");
        jPanel34.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, -1, -1));

        jRadioButton8.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jRadioButton8.setText("Female");
        jPanel34.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, -1, -1));

        jFormattedTextField23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jFormattedTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel34.add(jFormattedTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 270, 30));

        jTextField53.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField53.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel34.add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 270, -1));

        jTextField54.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField54.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jTextField54.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField54KeyReleased(evt);
            }
        });
        jPanel34.add(jTextField54, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 270, -1));

        jTextField55.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField55.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel34.add(jTextField55, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 270, -1));

        jLabel148.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel148.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel148.setText("Employee Name     :");
        jPanel34.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel149.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel149.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel149.setText("Delete");
        jLabel149.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel149.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel149MouseClicked(evt);
            }
        });
        jPanel34.add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 120, 40));

        jLabel150.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel150.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel150.setText("Update");
        jLabel150.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel150.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel150MouseClicked(evt);
            }
        });
        jPanel34.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 120, 40));

        jFormattedTextField24.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jFormattedTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel34.add(jFormattedTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 270, 30));

        jTable9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable9.setRowHeight(22);
        jTable9.setShowHorizontalLines(false);
        jTable9.setShowVerticalLines(false);
        jTable9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable9KeyPressed(evt);
            }
        });
        jScrollPane9.setViewportView(jTable9);

        jPanel34.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 540, 350));

        jLabel151.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel151.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel151.setText("Employee Id       :");
        jPanel34.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        jTextField57.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField57.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jTextField57.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField57KeyReleased(evt);
            }
        });
        jPanel34.add(jTextField57, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 270, -1));

        viewemp.getContentPane().add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        jDesktopPane1.add(viewemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 1070, 580));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Booking History");
        jDesktopPane1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 140, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("New booking");
        jDesktopPane1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 120, -1));

        jLabel36.setBackground(new java.awt.Color(0, 0, 0));
        jLabel36.setOpaque(true);
        jDesktopPane1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 710));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Add Employee");
        jDesktopPane1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 130, -1));

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setOpaque(true);
        jDesktopPane1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 90, 710));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("View Venue");
        jDesktopPane1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 120, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("View Employee");
        jDesktopPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 380, 140, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Add Venue");
        jDesktopPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 110, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/view emp.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(255, 255, 255)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 260, 120, 110));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/addven.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(255, 255, 255)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 120, 110));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/newbook.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(255, 255, 255)));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 120, 110));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/bookhis.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(255, 255, 255)));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 120, 110));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/view Venue.png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(255, 255, 255)));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 120, 110));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/addemp.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(255, 255, 255)));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 120, 110));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/event.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 700));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
addven.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
newbook.setVisible(true);        // TODO add your handling code here:
        try {
          Vector<String> header=new Vector<String>();  
          header.add("Booking Id");
          header.add("Type");
          header.add("Place");
          header.add("Booking Date");
          header.add("Total");
          header.add("Status");
          Vector<Vector<String>> data=new Vector<Vector<String>>();
          DBConnection db=new DBConnection();
          db.pstmt=db.con.prepareStatement("select bid,type,place,dt,total,status from booking where status='Pending'");
          db.rst=db.pstmt.executeQuery();
          while(db.rst.next())
          {
              Vector<String> temp=new Vector<String>();  
              temp.add(db.rst.getString(1));
              temp.add(db.rst.getString(2));
              temp.add(db.rst.getString(3));
              temp.add(db.rst.getString(4));
              temp.add(db.rst.getString(5));
              temp.add(db.rst.getString(6));
              data.add(temp);
          }
          jTable1.setModel(new DefaultTableModel(data,header));
          } catch (Exception e) {
          e.printStackTrace();
          }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
bookhis.setVisible(true);        // TODO add your handling code here:
        try {
          Vector<String> header=new Vector<String>();  
          header.add("Booking Id");
          header.add("Type");
          header.add("Place");
          header.add("Booking Date");
          header.add("Total");
          header.add("Status");
          Vector<Vector<String>> data=new Vector<Vector<String>>();
          DBConnection db=new DBConnection();
          db.pstmt=db.con.prepareStatement("select bid,type,place,dt,total,status from booking");
          db.rst=db.pstmt.executeQuery();
          while(db.rst.next())
          {
              Vector<String> temp=new Vector<String>();  
              temp.add(db.rst.getString(1));
              temp.add(db.rst.getString(2));
              temp.add(db.rst.getString(3));
              temp.add(db.rst.getString(4));
              temp.add(db.rst.getString(5));
              temp.add(db.rst.getString(6));
              data.add(temp);
          }
          jTable2.setModel(new DefaultTableModel(data,header));
          } catch (Exception e) {
          e.printStackTrace();
          }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
viewven.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked
int eid=100;
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
addemp.setVisible(true);
try {
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("select MAX(eid) from employee");
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {
            eid=db.rst.getInt(1)+1;
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
viewemp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked
File f;
Image b;
    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
try {JFileChooser jf=new JFileChooser();
jf.showOpenDialog(this);
f=jf.getSelectedFile();
b=ImageIO.read(f);
jLabel10.setText("");
jLabel10.setIcon(new ImageIcon(b.getScaledInstance(330,280,Image.SCALE_DEFAULT)));
}
catch(Exception e)
{
e.printStackTrace();
}
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
if(!Text(jTextField2.getText()))
{
    JOptionPane.showMessageDialog(this,"Invalid Name");
}
else if(!Address(jTextField3.getText()))
{
    JOptionPane.showMessageDialog(this,"Invalid Address");
}
else if(!PhoneNumber(jFormattedTextField2.getText()))
{
    JOptionPane.showMessageDialog(this,"Invalid Phone Number");
}
else if(!Number(jFormattedTextField3.getText()))
{
    JOptionPane.showMessageDialog(this,"Invalid Capacity");
}
else if(!Number(jFormattedTextField1.getText()))
{
    JOptionPane.showMessageDialog(this,"Invalid Rupees");
}
else
{
        DBConnection db=new DBConnection();  
            try {
              db.pstmt=db.con.prepareStatement("insert into venue values(?,?,?,?,?,?,?)");
              db.pstmt.setString(1,jTextField2.getText());
              db.pstmt.setString(2,jTextField3.getText());
              db.pstmt.setString(3,jFormattedTextField2.getText());
              db.pstmt.setString(4,jFormattedTextField3.getText());
              db.pstmt.setString(5,jComboBox1.getSelectedItem().toString());
              db.pstmt.setString(6,jFormattedTextField1.getText());
              FileInputStream q = new FileInputStream(f);
              db.pstmt.setBinaryStream(7,q,(int)f.length());
              int i=db.pstmt.executeUpdate();
              if(i>0)
              {
                JOptionPane.showMessageDialog(this,"Venue Added");
                jTextField2.setText("");
                jTextField3.setText("");
                jFormattedTextField2.setText("");
                jFormattedTextField1.setText("");
                jFormattedTextField3.setText("");
                jComboBox1.setSelectedIndex(0);
                jLabel10.setIcon(null);
                f=null;
                b=null;
              }
        } catch (Exception ex) {
        System.out.println("file not selected");
        } 
}
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel137MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel137MouseClicked
       if(!Text(jTextField48.getText()))
       {
       JOptionPane.showMessageDialog(this,"Invalid Name");
       }
       else if(!Aadhar(jTextField46.getText()))
       {
           JOptionPane.showMessageDialog(this,"Invalid Aadhar");
       }
       else if(!Text(jFormattedTextField8.getText()))
       {
           JOptionPane.showMessageDialog(this,"Invalid Designation");
       }
       else if(!PhoneNumber(jFormattedTextField22.getText()))
       {
           JOptionPane.showMessageDialog(this,"Invalid Number");
       }
       else if(!Email(jTextField47.getText()))
       {
           JOptionPane.showMessageDialog(this,"Invalid Email");
       }
       else if(!Address(jTextField50.getText()))
       {
           JOptionPane.showMessageDialog(this,"Invalid Address");
       }
       else{
        try {
         DBConnection db=new DBConnection();
         db.pstmt=db.con.prepareStatement("insert into employee values(?,?,?,?,?,?,?,?,?)");
         db.pstmt.setString(1,String.valueOf(eid));
         db.pstmt.setString(2,jTextField48.getText());
         db.pstmt.setString(3,jTextField46.getText());
         db.pstmt.setString(4,jFormattedTextField8.getText());
         String gen="";
         if(jRadioButton5.isSelected())
         {
         gen="Male";    
         }
         if(jRadioButton6.isSelected())
         {
         gen="Female";    
         }
         db.pstmt.setString(5,gen);
         db.pstmt.setString(6,jFormattedTextField22.getText());
         db.pstmt.setString(7,jTextField47.getText());
         SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
         db.pstmt.setString(8,sdf.format(jDateChooser1.getDate()));
         db.pstmt.setString(9,jTextField50.getText());
         int i=db.pstmt.executeUpdate();
         if(i>0)
         {
             try {
             DBConnection db1=new DBConnection();
             db1.pstmt=db1.con.prepareStatement("insert into login values(?,?,?)");
             db1.pstmt.setString(1,jTextField48.getText());
             db1.pstmt.setString(2,jPasswordField1.getText());
             db1.pstmt.setString(3,"Employee");
             int j=db1.pstmt.executeUpdate();
             if(j>0)
             {
                JOptionPane.showMessageDialog(this,"Employee Added.!");
             jTextField48.setText("");
             jTextField46.setText("");
             jFormattedTextField8.setText("");
             jFormattedTextField22.setText("");
             jTextField47.setText("");
             jDateChooser1.setDate(null);
             jTextField50.setText("");
             jRadioButton5.setSelected(true);
             jRadioButton6.setSelected(false);
             }
             
             } catch (Exception e) {
             }
         }
        } catch (Exception e) {
        e.printStackTrace();
        }}
    }//GEN-LAST:event_jLabel137MouseClicked

    private void jTextField54KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField54KeyReleased
          try {
          Vector<String> header=new Vector<String>();  
          header.add("Employee Id");
          header.add("Employee Name");
          header.add("Designation");
          Vector<Vector<String>> data=new Vector<Vector<String>>();
          String a=jTextField54.getText(); 
          DBConnection db=new DBConnection();
          db.pstmt=db.con.prepareStatement("select eid,ename,desig from employee where ename like '%"+a+"%'");
          db.rst=db.pstmt.executeQuery();
          while(db.rst.next())
          {
              Vector<String> temp=new Vector<String>();  
              temp.add(db.rst.getString(1));
              temp.add(db.rst.getString(2));
              temp.add(db.rst.getString(3));
              data.add(temp);
          }
          jTable9.setModel(new DefaultTableModel(data,header));
          } catch (Exception e) {
          e.printStackTrace();
          }
    }//GEN-LAST:event_jTextField54KeyReleased

    private void jTable9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable9KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
{
    int row=jTable9.getSelectedRow();
    try {
    DBConnection db=new DBConnection();
    db.pstmt=db.con.prepareStatement("select * from employee where eid='"+jTable9.getValueAt(row,0).toString()+"'");
    db.rst=db.pstmt.executeQuery();
    if(db.rst.next())
    {
        jTextField57.setText(db.rst.getString(1));
        jTextField52.setText(db.rst.getString(3));
        jFormattedTextField19.setText(db.rst.getString(4));
        String gen=db.rst.getString(5);
        if(gen.equals("Male"))
        {
        jRadioButton7.setSelected(true);    
        jRadioButton8.setSelected(false);    
        }
        if(gen.equals("Female"))
        {
        jRadioButton8.setSelected(true);    
        jRadioButton7.setSelected(false);    
        }
        jFormattedTextField24.setText(db.rst.getString(6));
        jTextField53.setText(db.rst.getString(7));
        jFormattedTextField23.setText(db.rst.getString(8));
        jTextField55.setText(db.rst.getString(9));
        
    }
    } catch (Exception e) {
    e.printStackTrace();
    }
}
    }//GEN-LAST:event_jTable9KeyPressed

    private void jTextField57KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField57KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField57KeyReleased

    private void jLabel150MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel150MouseClicked
        try {
        DBConnection db=new DBConnection();
        db.pstmt=db.con.prepareStatement("update employee set aadhar=?,desig=?,gen=?,mob=?,email=?,doj=?,addr=? where eid=?");
        db.pstmt.setString(8,jTextField57.getText());
        db.pstmt.setString(1,jTextField52.getText());
        db.pstmt.setString(2,jFormattedTextField19.getText());
        String gender="";
        if(jRadioButton7.isSelected())
        {
            gender="Male";
        }
        if(jRadioButton8.isSelected())
        {
            gender="Female";
        }
        db.pstmt.setString(3,gender);
        db.pstmt.setString(4,jFormattedTextField24.getText());
        db.pstmt.setString(5,jTextField53.getText());
        db.pstmt.setString(6,jFormattedTextField23.getText());
        db.pstmt.setString(7,jTextField55.getText());
        
        int i=db.pstmt.executeUpdate();
        if(i>0)
        {
            JOptionPane.showMessageDialog(this,"Employee Updated.!");
            jTextField57.setText("");
jTextField52.setText("");
jFormattedTextField19.setText("");
jFormattedTextField24.setText("");
jTextField53.setText("");
jFormattedTextField23.setText("");
jTextField55.setText("");

jRadioButton7.setSelected(false);
jRadioButton8.setSelected(false);
        }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel150MouseClicked

    private void jLabel149MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel149MouseClicked
try {
        DBConnection db=new DBConnection();
        db.pstmt=db.con.prepareStatement("delete from employee where eid=?");
        db.pstmt.setString(1,jTextField57.getText());
        int i=db.pstmt.executeUpdate();
        if(i>0)
        {
            JOptionPane.showMessageDialog(this,"Employee Deleted.!");
            jTextField57.setText("");
jTextField52.setText("");
jFormattedTextField19.setText("");
jFormattedTextField24.setText("");
jTextField53.setText("");
jFormattedTextField23.setText("");
jTextField55.setText("");
jRadioButton7.setSelected(false);
jRadioButton8.setSelected(false);
        }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel149MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
         try {
          Vector<String> header=new Vector<String>();  
          header.add("Venue Name");
          header.add("Address");
          header.add("Capacity");
          header.add("Rupees");
          Vector<Vector<String>> data=new Vector<Vector<String>>();
          String a=jComboBox5.getSelectedItem().toString();
          DBConnection db=new DBConnection();
          db.pstmt=db.con.prepareStatement("select venue,addr,capacity,rupees from venue where prefer='"+a+"'");
          db.rst=db.pstmt.executeQuery();
          while(db.rst.next())
          {
              Vector<String> temp=new Vector<String>();  
              temp.add(db.rst.getString(1));
              temp.add(db.rst.getString(2));
              temp.add(db.rst.getString(3));
              temp.add(db.rst.getString(4));
              data.add(temp);
          }
          jTable3.setModel(new DefaultTableModel(data,header));
          } catch (Exception e) {
          e.printStackTrace();
          }
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
int i=JOptionPane.showConfirmDialog(this,"logout..??","Event Management System",JOptionPane.YES_NO_OPTION);
if(i==0)
{
    new Home().setVisible(true);
    setVisible(false);
}
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
jTextField4.setText(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        try {
        DBConnection db=new DBConnection();
        db.pstmt=db.con.prepareStatement("select status from booking where bid='"+jTextField4.getText()+"'");
        db.rst=db.pstmt.executeQuery();
        if(db.rst.next())
        {
            jTextField5.setText(db.rst.getString(1));
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        try {
            DBConnection db=new DBConnection();
            db.pstmt=db.con.prepareStatement("update booking set status='"+jComboBox3.getSelectedItem().toString()+"' where bid='"+jTextField4.getText()+"'");
            int i=db.pstmt.executeUpdate();
            if(i>0)
            {
               JOptionPane.showMessageDialog(this,"Status Changed"); 
               jTextField4.setText("");
               jTextField5.setText("");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
jRadioButton5.setSelected(true);
jRadioButton6.setSelected(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
jRadioButton5.setSelected(false);
jRadioButton6.setSelected(true);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame addemp;
    private javax.swing.JInternalFrame addven;
    private javax.swing.JInternalFrame bookhis;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField22;
    private javax.swing.JFormattedTextField jFormattedTextField23;
    private javax.swing.JFormattedTextField jFormattedTextField24;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JInternalFrame newbook;
    private javax.swing.JInternalFrame viewemp;
    private javax.swing.JInternalFrame viewven;
    // End of variables declaration//GEN-END:variables
public boolean Text(String str){
        int j;
        int a;
        str=str.toUpperCase();
        if(" ".equals(str)||str.length()==0){
            return false;       
        }   //calculating error for given String
    else{
        for(j=1;j<=str.length();j++){
                                    a=(int)str.charAt(j-1);
                    if(a>=65&&a<=90||a==32){}
                    else     {       return !(a<65||a>90);}
        }   }
        return true;
    }
    
    public boolean PhoneNumber(String no){
        int j,ascii,a;
    if(no.length()==0){return false;    }                  //calculating error from given number
    else{
        for(int k=0;k<no.length();k++){
                ascii=(int)no.charAt(k);
                
           if(no.length()>10||no.length()<10){                return false;}
           else if(ascii<48||ascii>57){                return false;}
            else if(ascii>=48&&ascii<=57){ /*do nothing */ }
          } }
        return true;
    }
    public boolean Aadhar(String no){
        int j,ascii,a;
    if(no.length()==0){return false;    }                  //calculating error from given number
    else{
        for(int k=0;k<no.length();k++){
                ascii=(int)no.charAt(k);
                
           if(no.length()>12||no.length()<12){                return false;}
           else if(ascii<48||ascii>57){                return false;}
            else if(ascii>=48&&ascii<=57){ /*do nothing */ }
          } }
        return true;
    }
    
    
    public boolean Number(String no){
        int j,ascii,a;
    if(no.length()==0){
                    return false;    }                  //calculating error from given number
    else{
        for(int k=0;k<no.length();k++){
                ascii=(int)no.charAt(k);
            
           if(ascii<48||ascii>57){  
                return false;}
            else if(ascii>=48&&ascii<=57||ascii==46){ /*do nothing */ }
          } }
        return true;
    }
    public boolean Email(String email){
        int j;
        int a;
        int count=0;
        email=email.toUpperCase();
            if(email.length()==0||email.equals(" ")){
                return false;   }
            else{
                        for(j=1;j<=email.length();j++){
                                    a=(int)email.charAt(j-1);
                                    if(a==46)
                                        count++;
                                    else if(a==64)
                                        count++;
                                    if(count>2){     
                                        return false;}
                                    else if(a>=65||a<=90){}
                                    else            
                                            return !(a<64||a>90);
                }
            }
                        if(count==2)
                            return true;
                        else{    
                            return false;}
    }
    
    public boolean Address(String str){
        int j;
        int a;
        str=str.toUpperCase();
        if(" ".equals(str)||str.length()==0){   
        return false;        }   //calculating error for given String
    else{
        for(j=1;j<=str.length();j++){
                                    a=(int)str.charAt(j-1);
                    if(a>=65&&a<=90||a==47||a==44||a==45||a==39||a==32){}
                    else{   
                            return !(a<65||a>90);}
        }   }
        return true;
    }
}
