package Event;

import DB.DBConnection;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
    }String uname="";
    public Employee(String u) {
        initComponents();
        uname=u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        bookstat = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        newbook = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel49 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        bookhis = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        viewven = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        profile = new javax.swing.JInternalFrame();
        jPanel32 = new javax.swing.JPanel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel134 = new javax.swing.JLabel();
        jTextField46 = new javax.swing.JTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jFormattedTextField21 = new javax.swing.JFormattedTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jLabel135 = new javax.swing.JLabel();
        jFormattedTextField22 = new javax.swing.JFormattedTextField();
        jTextField49 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Logout");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 230, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Event Management System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 0, 489, 60));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Employee Module");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 245, 60));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookstat.setClosable(true);
        bookstat.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        bookstat.setTitle("Booking Status");
        bookstat.setVisible(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Booking Status     ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Search");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 100, 30));

        jTextField2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 280, -1));

        jTextField3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 280, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Booking Id            :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 20));

        jLabel38.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Status                    :");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        javax.swing.GroupLayout bookstatLayout = new javax.swing.GroupLayout(bookstat.getContentPane());
        bookstat.getContentPane().setLayout(bookstatLayout);
        bookstatLayout.setHorizontalGroup(
            bookstatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bookstatLayout.setVerticalGroup(
            bookstatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(bookstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 710, 280));

        newbook.setClosable(true);
        newbook.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        newbook.setTitle("New Booking");
        newbook.setVisible(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Booking New Event");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("No. of Guests        :");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jTextField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 280, -1));

        jTextField5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 280, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Step 2------------->");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, 20));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Event Place          :");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select-----", "Normal", "Royal" }));
        jComboBox3.setPreferredSize(new java.awt.Dimension(56, 30));
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 280, -1));

        jLabel39.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Event Type            :");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jComboBox4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select-----", "Marriage", "Meeting", "Auction", "Birthday", "Ring Ceremony", "Kitty Party" }));
        jComboBox4.setPreferredSize(new java.awt.Dimension(56, 30));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 280, -1));

        jLabel40.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Date                       :");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jLabel41.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Equipment           :");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, 20));

        jLabel46.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Step 1------------->");
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, 20));

        jLabel47.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Booking ID              :");
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 20));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox1.setText("Mike and Speakers");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox2.setText("DJ");
        jPanel4.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox3.setText("Stage");
        jPanel4.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Step 3------------->");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, 20));

        jLabel48.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Food  Type      :");
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, -1, 20));

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox4.setText("BreakFast");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox5.setText("Lunch");
        jPanel4.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, -1, -1));

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox6.setText("Dinner");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, -1, -1));

        jCheckBox7.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox7.setText("Tea and Snacks");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jRadioButton1.setText("Only Veg");
        jPanel4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 607, -1, 40));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jRadioButton2.setText("Veg and Non Veg");
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 607, -1, 40));

        jLabel49.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Food                    :");
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, 20));

        jComboBox7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.setPreferredSize(new java.awt.Dimension(56, 30));
        jPanel4.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 280, -1));

        jLabel50.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Step 4------------->");
        jPanel4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 720, -1, 20));

        jLabel51.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Decorations            :");
        jPanel4.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 720, -1, 20));

        jLabel52.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Lightings      :");
        jPanel4.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 770, -1, 20));

        jComboBox8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select-----", "Normal", "Royal" }));
        jComboBox8.setPreferredSize(new java.awt.Dimension(56, 30));
        jPanel4.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 770, 280, -1));

        jLabel53.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Flowers         :");
        jPanel4.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 820, -1, 20));

        jComboBox9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select-----", "Normal", "Royal" }));
        jComboBox9.setPreferredSize(new java.awt.Dimension(56, 30));
        jPanel4.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 820, 280, -1));

        jLabel54.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Seating         :");
        jPanel4.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 870, -1, 20));

        jComboBox10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select-----", "Normal", "Royal" }));
        jComboBox10.setPreferredSize(new java.awt.Dimension(56, 30));
        jPanel4.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 870, 280, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel55.setBackground(new java.awt.Color(0, 0, 0));
        jLabel55.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Total                   :");

        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(255, 255, 255)));

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Calculate");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel55)
                .addGap(38, 38, 38)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 910, 1030, 50));

        jLabel56.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Submit");
        jLabel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 770, 120, 40));
        jPanel4.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 280, 30));

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout newbookLayout = new javax.swing.GroupLayout(newbook.getContentPane());
        newbook.getContentPane().setLayout(newbookLayout);
        newbookLayout.setHorizontalGroup(
            newbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        newbookLayout.setVerticalGroup(
            newbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newbookLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jDesktopPane1.add(newbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1060, 610));

        bookhis.setClosable(true);
        bookhis.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        bookhis.setTitle("Booking History");
        bookhis.setVisible(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Bookings");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jScrollPane2.setBorder(null);

        jTable2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setRowHeight(22);
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 980, 470));

        javax.swing.GroupLayout bookhisLayout = new javax.swing.GroupLayout(bookhis.getContentPane());
        bookhis.getContentPane().setLayout(bookhisLayout);
        bookhisLayout.setHorizontalGroup(
            bookhisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bookhisLayout.setVerticalGroup(
            bookhisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(bookhis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1060, 700));

        viewven.setClosable(true);
        viewven.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        viewven.setTitle("View Venue");
        viewven.setVisible(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Venues");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel42.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Venue Type         :");
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jComboBox5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select-----", "Marriage", "Meeting", "Auction", "Birthday", "Ring Ceremony", "Kitty Party" }));
        jComboBox5.setPreferredSize(new java.awt.Dimension(56, 30));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 280, 40));

        jLabel43.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Image           :");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jComboBox6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.setPreferredSize(new java.awt.Dimension(56, 30));
        jComboBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox6MouseClicked(evt);
            }
        });
        jPanel6.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 280, 40));

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 215, 280, 30));

        jLabel44.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Venue                    :");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 480, 240));

        jLabel45.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Cost                      :");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        javax.swing.GroupLayout viewvenLayout = new javax.swing.GroupLayout(viewven.getContentPane());
        viewven.getContentPane().setLayout(viewvenLayout);
        viewvenLayout.setHorizontalGroup(
            viewvenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        viewvenLayout.setVerticalGroup(
            viewvenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.add(viewven, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1060, 700));

        profile.setClosable(true);
        profile.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        profile.setTitle("Profile");
        profile.setVisible(false);
        profile.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel124.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel124.setText("Id                        :");
        jPanel32.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel125.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel125.setText("Aadhar No.               :");
        jPanel32.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel126.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel126.setText("Designation         :");
        jPanel32.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel127.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel127.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel127.setText("Gender                     :");
        jPanel32.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel128.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel128.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel128.setText("Mobile Number       :");
        jPanel32.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jLabel129.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel129.setText("Email Address           :");
        jPanel32.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        jLabel130.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel130.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel130.setText("Date Of Joining          :");
        jPanel32.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        jLabel132.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel132.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel132.setText("Address                    :");
        jPanel32.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));

        jLabel134.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel134.setText("My Profile");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(jLabel134)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel134, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        jTextField46.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField46.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel32.add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 270, -1));

        jFormattedTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jFormattedTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel32.add(jFormattedTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 270, 30));

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jRadioButton5.setText("Male");
        jPanel32.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jRadioButton6.setText("Female");
        jPanel32.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jFormattedTextField21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jFormattedTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel32.add(jFormattedTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 270, 30));

        jTextField47.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField47.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel32.add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 270, -1));

        jTextField48.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField48.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel32.add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 270, -1));

        jTextField50.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField50.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel32.add(jTextField50, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 270, -1));

        jLabel135.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel135.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel135.setText("Name                        :");
        jPanel32.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jFormattedTextField22.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jFormattedTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel32.add(jFormattedTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 270, 30));

        jTextField49.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jTextField49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField49.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 51, 0)));
        jPanel32.add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 270, -1));

        profile.getContentPane().add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        jDesktopPane1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 1070, 580));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Booking History");
        jDesktopPane1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 140, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Book An Event");
        jDesktopPane1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 140, -1));

        jLabel36.setBackground(new java.awt.Color(0, 0, 0));
        jLabel36.setOpaque(true);
        jDesktopPane1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 710));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Booking Status");
        jDesktopPane1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, 130, -1));

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setOpaque(true);
        jDesktopPane1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 90, 710));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("View Venue");
        jDesktopPane1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 120, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("My Profile");
        jDesktopPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 110, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/profile.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(0, 0, 0)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 120, 110));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/bookemp.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(0, 0, 0)));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 120, 110));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/bookhisemp.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(0, 0, 0)));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 120, 110));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/viewvenemp.png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(0, 0, 0)));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 120, 110));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/statusemp.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(0, 0, 0)));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 260, 120, 110));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event/even-management-1.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
profile.setVisible(true);
    try {
    DBConnection db=new DBConnection();
    db.pstmt=db.con.prepareStatement("select * from employee where ename='"+uname+"'");
    db.rst=db.pstmt.executeQuery();
    if(db.rst.next())
    {
        jTextField48.setText(db.rst.getString(1));
        jTextField49.setText(db.rst.getString(2));
        jTextField46.setText(db.rst.getString(3));
        jFormattedTextField8.setText(db.rst.getString(4));
        String gen=db.rst.getString(5);
        if(gen.equals("Male"))
        {
        jRadioButton5.setSelected(true);    
        jRadioButton6.setSelected(false);    
        }
        if(gen.equals("Female"))
        {
        jRadioButton6.setSelected(true);    
        jRadioButton5.setSelected(false);    
        }
        jFormattedTextField22.setText(db.rst.getString(6));
        jTextField47.setText(db.rst.getString(7));
        jFormattedTextField21.setText(db.rst.getString(8));
        jTextField50.setText(db.rst.getString(9));
            }
    } catch (Exception e) {
    e.printStackTrace();
    }

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        newbook.setVisible(true);        // TODO add your handling code here:
        Date d=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("ddMMyyHHmm");
       jTextField4.setText(sdf.format(d));
      
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        bookhis.setVisible(true);        // TODO add your handling code here:
        try {
          Vector<String> header=new Vector<String>();  
          header.add("Booking Id");
          header.add("Type");
          header.add("Place");
          header.add("Booking Date");
          header.add("Total");
          header.add("Status");
          Vector<Vector<String>> data=new Vector<Vector<String>>();
          DBConnection db=new DBConnection();
          db.pstmt=db.con.prepareStatement("select bid,type,place,dt,total,status from booking");
          db.rst=db.pstmt.executeQuery();
          while(db.rst.next())
          {
              Vector<String> temp=new Vector<String>();  
              temp.add(db.rst.getString(1));
              temp.add(db.rst.getString(2));
              temp.add(db.rst.getString(3));
              temp.add(db.rst.getString(4));
              temp.add(db.rst.getString(5));
              temp.add(db.rst.getString(6));
              data.add(temp);
          }
          jTable2.setModel(new DefaultTableModel(data,header));
          } catch (Exception e) {
          e.printStackTrace();
          }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        viewven.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        bookstat.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
int i=JOptionPane.showConfirmDialog(this,"logout..??","Event Management System",JOptionPane.YES_NO_OPTION);
if(i==0)
{
    new Home().setVisible(true);
    setVisible(false);
}
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        try {
          jComboBox6.removeAllItems();
          jComboBox6.addItem("Select-----");
          DBConnection db=new DBConnection();
          db.pstmt=db.con.prepareStatement("select venue from venue where prefer='"+jComboBox5.getSelectedItem().toString()+"'");
          db.rst=db.pstmt.executeQuery();
          while(db.rst.next())
          {
              jComboBox6.addItem(db.rst.getString(1));
          }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed
ImageIcon format;
    private void jComboBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox6MouseClicked
        String a="";
        try {
        a=jComboBox6.getSelectedItem().toString();
        } catch (Exception e) {
        }
        try {
           DBConnection db=new DBConnection();
           db.pstmt=db.con.prepareStatement("select rupees,image from venue where venue='"+a+"' and prefer='"+jComboBox5.getSelectedItem().toString()+"'");
           db.rst=db.pstmt.executeQuery();
           if(db.rst.next())
           {
               jTextField1.setText(db.rst.getString(1));
               byte[] id=db.rst.getBytes(2);
               format=new ImageIcon(id);
               Image mm=format.getImage();
               Image m2=mm.getScaledInstance(jLabel4.getWidth(),jLabel4.getHeight(),Image.SCALE_SMOOTH);
               ImageIcon im=new ImageIcon(m2);
               jLabel4.setIcon(im);
           }
        } catch (Exception e) {
        e.printStackTrace();}
    }//GEN-LAST:event_jComboBox6MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        double t=0;
        double a=Double.parseDouble(jTextField5.getText());
        if(jCheckBox2.isSelected())
          {
             t=t+2000;
          }
          else
          {
             
          }
          
          if(jCheckBox3.isSelected())
          {
          t=t+20000;
          }
          else
          {
              
          }
          
          if(jCheckBox1.isSelected())
          {
          t=t+2000;
          }
          else
          {
          
          }
          
          if(jCheckBox4.isSelected())
          {
          t=t+a*50;
          }
          else
          {
              
          }
          
          if(jCheckBox5.isSelected())
          {
          t=t+a*150;
          }
          else
          {
          
          }

          if(jCheckBox7.isSelected())
          {
t=t+a*25;
          }
          else
          {
        
          }
        
          if(jCheckBox6.isSelected())
          {
        t=t+a*150;
          }
          else
          {
          
          }
          if(jComboBox3.getSelectedItem().toString().equals("Royal"))
          {
              t=t*2;
          }
          if(jComboBox8.getSelectedItem().toString().equals("Royal"))
          {
              t=t+20000;
          }
          else
          {
              t=t+10000;
          }
          if(jComboBox9.getSelectedItem().toString().equals("Royal"))
          {
              t=t+20000;
          }
          else
          {
              t=t+10000;
          }
          if(jComboBox10.getSelectedItem().toString().equals("Royal"))
          {
              t=t+20000;
          }
          else
          {
              t=t+10000;
          }
          jTextField7.setText(String.valueOf(t));
          
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
try {
          DBConnection db=new DBConnection();
          db.pstmt=db.con.prepareStatement("insert into booking values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
          db.pstmt.setString(1,jTextField4.getText());
          db.pstmt.setString(2,jComboBox4.getSelectedItem().toString());
          db.pstmt.setString(3,jComboBox7.getSelectedItem().toString());
          SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
          db.pstmt.setString(5,sdf.format(jDateChooser1.getDate()));
          String a="";
          if(jCheckBox2.isSelected())
          {
              a="Yes";
          }
          else
          {
              a="No";
          }
          String b="";
          if(jCheckBox3.isSelected())
          {
              b="Yes";
          }
          else
          {
              b="No";
          }
          String c="";
          if(jCheckBox1.isSelected())
          {
              c="Yes";
          }
          else
          {
              c="No";
          }
          String d="";
          if(jCheckBox4.isSelected())
          {
              d="Yes";
          }
          else
          {
              d="No";
          }
          String e="";
          if(jCheckBox5.isSelected())
          {
              e="Yes";
          }
          else
          {
              e="No";
          }
          String f="";
          if(jCheckBox7.isSelected())
          {
              f="Yes";
          }
          else
          {
              f="No";
          }
          String g="";
          if(jCheckBox6.isSelected())
          {
              g="Yes";
          }
          else
          {
              g="No";
          }
          String veg="";
          if(jRadioButton1.isSelected())
          {
              veg="Veg";
          }
          if(jRadioButton2.isSelected())
          {
              veg="NonVeg";
          }
          db.pstmt.setString(6,a);
          db.pstmt.setString(7,b);
          db.pstmt.setString(8,c);
          db.pstmt.setString(9,d);
          db.pstmt.setString(10,e);
          db.pstmt.setString(11,f);
          db.pstmt.setString(12,g);
          db.pstmt.setString(13,veg);
          db.pstmt.setString(14,jComboBox3.getSelectedItem().toString());
          db.pstmt.setString(15,jComboBox8.getSelectedItem().toString());
          db.pstmt.setString(16,jComboBox9.getSelectedItem().toString());
          db.pstmt.setString(17,jComboBox10.getSelectedItem().toString());
          db.pstmt.setString(18,jTextField7.getText());
          db.pstmt.setString(19,"Pending");
          int i=db.pstmt.executeUpdate();
          if(i>0)
          {
              JOptionPane.showMessageDialog(this,"Booking Confirmed. Status-Pending");
Date x=new Date();
        SimpleDateFormat s1df=new SimpleDateFormat("ddMMyyHHmm");
        jTextField4.setText(s1df.format(x));
        jComboBox4.setSelectedIndex(0);
        jComboBox7.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox8.setSelectedIndex(0);
        jComboBox9.setSelectedIndex(0);
        jComboBox10.setSelectedIndex(0);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jTextField5.setText("");
        jDateChooser1.setDate(null);
        jTextField7.setText("");
          }
          else
          {
              JOptionPane.showMessageDialog(this,"Technical Fault");
          }
          
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel56MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        try {
        DBConnection db=new DBConnection();
        db.pstmt=db.con.prepareStatement("select status from booking where bid='"+jTextField2.getText()+"'");
        db.rst=db.pstmt.executeQuery();
        if(db.rst.next())
        {
            jTextField3.setText(db.rst.getString(1));
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        try {
          jComboBox7.removeAllItems();
          jComboBox7.addItem("Select-----");
          DBConnection db=new DBConnection();
          db.pstmt=db.con.prepareStatement("select venue from venue where prefer='"+jComboBox4.getSelectedItem().toString()+"'");
          db.rst=db.pstmt.executeQuery();
          while(db.rst.next())
          {
              jComboBox7.addItem(db.rst.getString(1));
          }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
if(!Number(jTextField5.getText()))
{
    JOptionPane.showMessageDialog(this,"Please Input Numbers Only");
}
    }//GEN-LAST:event_jTextField5FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame bookhis;
    private javax.swing.JInternalFrame bookstat;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFormattedTextField jFormattedTextField21;
    private javax.swing.JFormattedTextField jFormattedTextField22;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JInternalFrame newbook;
    private javax.swing.JInternalFrame profile;
    private javax.swing.JInternalFrame viewven;
    // End of variables declaration//GEN-END:variables
public boolean Text(String str){
        int j;
        int a;
        str=str.toUpperCase();
        if(" ".equals(str)||str.length()==0){
            return false;       
        }   //calculating error for given String
    else{
        for(j=1;j<=str.length();j++){
                                    a=(int)str.charAt(j-1);
                    if(a>=65&&a<=90||a==32){}
                    else     {       return !(a<65||a>90);}
        }   }
        return true;
    }
    
    public boolean PhoneNumber(String no){
        int j,ascii,a;
    if(no.length()==0){return false;    }                  //calculating error from given number
    else{
        for(int k=0;k<no.length();k++){
                ascii=(int)no.charAt(k);
                
           if(no.length()>10||no.length()<10){                return false;}
           else if(ascii<48||ascii>57){                return false;}
            else if(ascii>=48&&ascii<=57){ /*do nothing */ }
          } }
        return true;
    }
    public boolean Aadhar(String no){
        int j,ascii,a;
    if(no.length()==0){return false;    }                  //calculating error from given number
    else{
        for(int k=0;k<no.length();k++){
                ascii=(int)no.charAt(k);
                
           if(no.length()>12||no.length()<12){                return false;}
           else if(ascii<48||ascii>57){                return false;}
            else if(ascii>=48&&ascii<=57){ /*do nothing */ }
          } }
        return true;
    }
    
    
    public boolean Number(String no){
        int j,ascii,a;
    if(no.length()==0){
                    return false;    }                  //calculating error from given number
    else{
        for(int k=0;k<no.length();k++){
                ascii=(int)no.charAt(k);
            
           if(ascii<48||ascii>57){  
                return false;}
            else if(ascii>=48&&ascii<=57||ascii==46){ /*do nothing */ }
          } }
        return true;
    }
    public boolean Email(String email){
        int j;
        int a;
        int count=0;
        email=email.toUpperCase();
            if(email.length()==0||email.equals(" ")){
                return false;   }
            else{
                        for(j=1;j<=email.length();j++){
                                    a=(int)email.charAt(j-1);
                                    if(a==46)
                                        count++;
                                    else if(a==64)
                                        count++;
                                    if(count>2){     
                                        return false;}
                                    else if(a>=65||a<=90){}
                                    else            
                                            return !(a<64||a>90);
                }
            }
                        if(count==2)
                            return true;
                        else{    
                            return false;}
    }
    
    public boolean Address(String str){
        int j;
        int a;
        str=str.toUpperCase();
        if(" ".equals(str)||str.length()==0){   
        return false;        }   //calculating error for given String
    else{
        for(j=1;j<=str.length();j++){
                                    a=(int)str.charAt(j-1);
                    if(a>=65&&a<=90||a==47||a==44||a==45||a==39||a==32){}
                    else{   
                            return !(a<65||a>90);}
        }   }
        return true;
    }
}
